version: "3.7"

services:

    service_1:
        build: ./Service_1
        image: mmcgarrigle/service_1
        container_name: service_1
        ports:
            - "5000:5000"
        networks:
            - mmcgarrigle_network
        depends_on:
            - service_4

    service_2:
        build: ./Service_2
        image: mmcgarrigle/service_2
        container_name: service_2
        networks:
            - mmcgarrigle_network
        
    service_3:
        build: ./Service_3
        image: mmcgarrigle/service_3
        container_name: service_3
        networks:
            - mmcgarrigle_network
        
    service_4:
        build: ./Service_4
        image: mmcgarrigle/service_4
        container_name: service_4
        networks:
            - mmcgarrigle_network
        depends_on:
            - service_2
            - service_3
        
networks:
    mmcgarrigle_network:
        driver: bridge

